import { Subscription } from 'rxjs';
import { OnDestroy, OnInit } from '@angular/core';
import { MatSelectChange, MatSnackBar } from '@angular/material';
import { MangolLayer } from './../../classes/layer.class';
import { MangolConfigFeatureInfoItem } from './../../interfaces/config-toolbar.interface';
import { MangolFeatureIntoService } from './feature-info.service';
import { MangolMap } from '../../classes/map.class';
import * as ol from 'openlayers';
export declare class MangolFeatureInfoComponent implements OnInit, OnDestroy {
    private featureInfoService;
    snackBar: MatSnackBar;
    class: string;
    map: MangolMap;
    opts: MangolConfigFeatureInfoItem;
    maxFeatures: number;
    cursorStyle: string;
    placeholder: string;
    zoomOnRowClick: boolean;
    highlightFeatures: boolean;
    layers: MangolLayer[];
    selected: MangolLayer;
    hoverLayer: ol.layer.Vector;
    clickEvent: any;
    features: ol.Feature[];
    geojson: ol.format.GeoJSON;
    activateStateSubscription: Subscription;
    constructor(featureInfoService: MangolFeatureIntoService, snackBar: MatSnackBar);
    ngOnInit(): void;
    ngOnDestroy(): void;
    onSelectionChange(evt: MatSelectChange): void;
    openSnackBar(message: string, action: string): void;
    onFeatureSelected(evt: ol.Feature): void;
    private _addHoverLayer();
    private _removeHoverLayer();
    private _getQueryableLayers();
    private _setCursor(cursorType);
    private _getFeatureInfoUrl(source, coordinate, resolution, srs);
    private _deactivateClick();
    private _activateClick(layer);
}
